### ISSUE TITLE
loadTemplates blows up if there are "too many" templates

### ISSUE THREAD

**Issue by emhoracek** [positiondev/larceny#15]
Eli found this working on his branch on a Linux machine. He got an "openFile: Resource exhausted (Too many open files)" error wile loading templates.

**Comment by dbp** [comment]
Ooops! We must be forgetting to close files? Odd. I don't remember actually calling "openFile". Oh! maybe it's because we are using lazy text? https://github.com/positiondev/larceny/blob/master/src/Web/Larceny.hs#L204

**Comment by emhoracek** [comment]
Should be fixed now, but I'm sure how to test, since I can't even reproduce the issue on my computer.

**Comment by emhoracek** [comment]
This was fixed by ca281e81aa499fca348d8391d6fe0ace0f3d1593
