### ISSUE TITLE
Allow "opening up" of tags to include surrounding text

### ISSUE THREAD

**Issue by dhartunian** [positiondev/larceny#45]
Could be useful when things are missing to be able to replace this:

```
<div>Name: <translatorName /></div>
``` 
which can get rendered as `<div>Name: </div>`

with 
```
<translatorName><div>Name: <larceny:tag:content /></div></translatorName>
```

which could nicely remove the `Name: ` part when the tag is missing.

**Comment by emhoracek** [comment]
What do you think about https://github.com/positiondev/larceny/issues/50 as an alternative?

**Comment by emhoracek** [comment]
Since we went with #50 to accomplish this, I'm going to close.
